server:
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/project
        username: jmlee
        password: wjdals12!!
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 3000
            max-lifetime: 180000
    #jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
       # hibernate:
        #    ddl-auto: update # 개발중일때는 update, 운영중일땐 none 이나 validate
    #    show-sql: true
    #    properties:
    #        hibernate:
    #            format_sql: true # sql 코드가 정렬되서 나옴
    thymeleaf:
        cache: false # html cache를 끔(반영이 바로 되도록)
        prefix: classpath:/templates/
        
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
mybatis:
    configLocation: classpath:/mybatis-config.xml
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package : com.ecommerce.project.dto